services:
  web:
    image: php:8.3-apache
    container_name: belajar-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: belajar-web-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belajar-web-db
      MYSQL_USER: belajar-web
      MYSQL_PASSWORD: noroot
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: belajar-web-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db      
    depends_on:
      - db

volumes:
  mysql_data: